// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIg_lf0OsK7_5SHsvRkqV5Egym7FlMJLY',
    appId: '1:179533021868:web:9787c2f76e803277bf5509',
    messagingSenderId: '179533021868',
    projectId: 'ergata-71339',
    authDomain: 'ergata-71339.firebaseapp.com',
    storageBucket: 'ergata-71339.appspot.com',
    measurementId: 'G-6HJ4MXCFBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLkb_3qoI3ESEx4nDz9QVCYE8oRgV0TbU',
    appId: '1:179533021868:android:01e49a010d6c34a6bf5509',
    messagingSenderId: '179533021868',
    projectId: 'ergata-71339',
    storageBucket: 'ergata-71339.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZhUvJmG0XEhYy0opa1gYmHFtNClMiLH0',
    appId: '1:179533021868:ios:df5f5e55ee250faebf5509',
    messagingSenderId: '179533021868',
    projectId: 'ergata-71339',
    storageBucket: 'ergata-71339.appspot.com',
    iosBundleId: 'com.example.ergata',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZhUvJmG0XEhYy0opa1gYmHFtNClMiLH0',
    appId: '1:179533021868:ios:ffd0d0f27ad10c19bf5509',
    messagingSenderId: '179533021868',
    projectId: 'ergata-71339',
    storageBucket: 'ergata-71339.appspot.com',
    iosBundleId: 'com.example.ergata.RunnerTests',
  );
}
